#!/usr/bin/env ruby

DASHBOARD_URL = "https://strobe.geckoboard.com/dashboard/loop/419F6312EA25D40B/"
DASHBOARD_FREE_URL = "https://strobe.geckoboard.com/dashboard/loop/753D66F7051F7BDB/"

$:.push File.expand_path("../lib", __FILE__)
require 'helpers'

usage "Show Dashboard in Chrome. Pass 'url' to get the url. Pass 'free' to show the free url with ads."

url = ARGV.include?("free") ? DASHBOARD_FREE_URL : DASHBOARD_URL

if ARGV.include?("url")
  puts url
  exit
end

chrome_ps = `ps x`.split("\n").find { |ps| ps[/Google Chrome/] }
if chrome_ps
  chrome_pid = Integer(chrome_ps[/^\s*\d+/])
  Process.kill 15, chrome_pid rescue nil
end

# Give Chrome time to shut down
sleep 0.5

ascript <<-EOD
  tell application "Google Chrome"
    set URL of active tab of window 1 to "#{url}"
    delay 0.5
    activate
    tell application "System Events"
      key down {command}
      key down {shift}
      keystroke "f"
      key up {shift}
      key up {command}
    end tell
  end tell
EOD
