#!/usr/bin/env ruby

require 'net/http'
require 'json'

hash = JSON.parse Net::HTTP.get URI('http://www.reddit.com/r/aww.json')

data = hash['data']['children']
data = data.select { |d| d['kind'] == 't3' }
data = data.map { |d| d['data'] }
data = data.select { |d| d['domain'] == 'i.imgur.com' }

random = data[rand(data.length)]

puts random['url']
