#!/usr/bin/env ruby

require 'cgi'
require 'net/http'
require 'json'

$:.push File.dirname(__FILE__)
require 'helpers/core'

usage "Obtain information about RubyGems: !gem <name>"

unless ARGV[0]
  puts "What gem, bro?"
  exit
end

uri = URI("http://rubygems.org/api/v1/gems/#{CGI.escape(ARGV[0])}.json")

begin
  json = JSON.parse Net::HTTP.get(uri)
rescue JSON::ParserError
  puts "Sorry bro, there's no '#{ARGV[0]}' gem"
  exit 0
end

puts "#{json['name']} #{json['version']}: #{json['info']} (#{json['downloads']} downloads)"
