#!/usr/bin/env ruby

$:.push File.dirname(__FILE__)
require 'helpers/core'
require 'helpers/db'

USAGE = "!remember <key>: <value>"
usage USAGE

def halt
  puts "Usage: #{USAGE}"
  exit 1
end

halt unless input
key, value = input.split(/\s+is\s+/)
halt unless value

key.strip!
key.downcase!
value.strip!

DB[:memory][key] = value
puts "Okay, I remember \"#{key}\" is \"#{value}\""
