#!/usr/bin/env ruby

$:.push File.dirname(__FILE__)
require 'helpers/core'
require 'helpers/mac'

usage "Say something using the given voice"

if ARGV.size < 2
  puts "Give me a voice and something to say"
else
  say(*ARGV[1..-1], :voice => ARGV[0].gsub('_', ' '))
end
